In [2]:
import pandas as pd
import numpy as np
datasixm = pd.read_csv(r"/Users/yeonsookim/Desktop/poi rec/data/coex_users_6m_gt_50_visits_20180130.csv", sep=',', skiprows = 3)
datasixm

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
0,2017-09-19 13,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,219422,스타필드 코엑스몰점/샤이바나,코엑스몰점,Western Food Restaurants,"37.5120936275,127.059262544",서울특별시 강남구 삼성1동
1,2017-09-19 21,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,75192,롯데백화점 강남점,/슈즈에비뉴,Department Store,"37.49698724,127.05390349",서울 강남구 대치동 937
2,2017-09-21 15,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,212943,분당선 왕십리역,수원방면 4-3,Subway Station,"37.5605928695,127.038793266",서울 성동구 행당동 168-151
3,2017-09-23 13,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,219966,스타필드 코엑스몰점/Paul Bassett,코엑스몰점,Coffee Shop,"37.5138499364,127.059908286",서울 강남구 삼성1동
4,2017-09-23 14,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,218692,스타필드 코엑스몰점,/공수간/CJFOODWOTLD,Outlet/ Shopping Mall,"37.5117460309,127.058322765",서울 강남구 삼성동 159-9
...,...,...,...,...,...,...,...,...,...
5378779,2018-01-04 12,zzGqvqri8YjMoe4Q26qlYJ1twJyL4XypzReIFT0hX6o=,T1,183177,뉴코아아울렛 괴정점,/아동/유아/놀이터/고객서비스센터,Outlet/ Shopping Mall,"35.0991100944,128.994107209",부산 사하구 괴정동 1012-2
5378780,2018-01-04 13,zzGqvqri8YjMoe4Q26qlYJ1twJyL4XypzReIFT0hX6o=,T1,150750,NATURE REPUBLIC,괴정점,Cosmetics Shop,"35.0994104622,128.993924484",부산 사하구 괴정동 1012-14
5378781,2018-01-04 14,zzGqvqri8YjMoe4Q26qlYJ1twJyL4XypzReIFT0hX6o=,T1,150760,스타벅스,부산괴정역점,Coffee Shop,"35.0983727483,128.994229585",부산 사하구 괴정동 961-6
5378782,2018-01-04 16,zzGqvqri8YjMoe4Q26qlYJ1twJyL4XypzReIFT0hX6o=,T1,150688,투썸플레이스,부산괴정점,Coffee Shop,"35.0998446688,128.992914588",부산 사하구 괴정동 971-9
5378783,2018-01-04 16,zzGqvqri8YjMoe4Q26qlYJ1twJyL4XypzReIFT0hX6o=,T1,364939,소미돈까스,대신점,Western Food Restaurants,"35.1099985156,129.017257097",부산 서구 서대신동2가 120-7

In [3]:
dataonem = pd.read_csv(r"/Users/yeonsookim/Desktop/poi rec/data/sample_data_coex_visitors_visits_20171201_20180105.csv", sep=',', skiprows = 3)
dataonem

,local_datehour,pid,placename,tag,cat,lat_lng,addr,hash_uid
0,2017-12-05 16,309678,현아마트,NaN,Supermarket,"35.1722490127,126.906719065",광주 북구 중흥동 320-1,AACepmlRCBduWs47hBiedMwYEXaoAdQfQ+gZuNjcJnE=
1,2017-12-08 13,307794,피자스쿨,전대정문점,Pizza,"35.1714482921,126.904695508",광주 북구 신안동 210-1,AACepmlRCBduWs47hBiedMwYEXaoAdQfQ+gZuNjcJnE=
2,2017-12-09 00,23467,CU,등촌원룸점,Convenience Store,"37.5565109631,126.860730127",서울 강서구 등촌동 636,AACepmlRCBduWs47hBiedMwYEXaoAdQfQ+gZuNjcJnE=
3,2017-12-09 12,86057,서울9호선 증미역,종합운동장 방면 2-4,Subway Station,"37.5580690136,126.860647984",서울 강서구 등촌동 666-40,AACepmlRCBduWs47hBiedMwYEXaoAdQfQ+gZuNjcJnE=
4,2017-12-09 12,86066,서울9호선 신목동역,종합운동장 방면 2-4,Subway Station,"37.5441703286,126.88310042",서울 양천구 목동 138-19,AACepmlRCBduWs47hBiedMwYEXaoAdQfQ+gZuNjcJnE=
...,...,...,...,...,...,...,...,...
773510,2018-01-02 11,255314,유명국양평해장국,NaN,Korean Food Restaurants,"37.5164864303,127.018625519",서울 서초구 잠원동 13-12,//kIAIl1UY8yg6bTw21m0ubi1fOG1jVal7Z8FDQv19o=
773511,2018-01-03 15,218727,스타필드 코엑스몰점,/케리마켓/ANLE COFFEE,Outlet/ Shopping Mall,"37.509522385,127.05979798",서울 강남구 삼성동 159-9,//kIAIl1UY8yg6bTw21m0ubi1fOG1jVal7Z8FDQv19o=
773512,2018-01-04 15,88341,서울6호선 합정역,응암순환행 6-4,Subway Station,"37.5489424459,126.913731247",서울 마포구 합정동 420,//kIAIl1UY8yg6bTw21m0ubi1fOG1jVal7Z8FDQv19o=
773513,2018-01-04 15,449254,스타벅스,은평이마트점,Coffee Shop,"37.6004279186,126.920495389",NaN,//kIAIl1UY8yg6bTw21m0ubi1fOG1jVal7Z8FDQv19o=
773514,2018-01-04 16,9814,이마트 은평점,/비식품,Discount Department Store,"37.6005156078,126.920202412",서울 은평구 응암동 90-1,//kIAIl1UY8yg6bTw21m0ubi1fOG1jVal7Z8FDQv19o=

In [4]:
historynum = datasixm['hash_uid'].value_counts()
historynum

hash_uid
Uru5Avt875xZfeIlo5SijjLrq4DNsrF71gZQeJXrP8I=    8720
HmqVYaE6h9te/c29FCN6kdrOSwgHb/DaB5IEQ0f5EM8=    6617
gl/kKohNuZxHxWjV7kt041f5db5xLoH0aH0A3Zvm6Ro=    5287
kmZjtQg48O7hKADuqvIxzlWOkI/hosHdu4W4xb2JrAA=    5216
RPBB5wDJsF13FJqE0obViewGv4DsGu6g46hgnUzrgcQ=    4943
                                                ...
avmPZAKkpXbmdzt/h8ix+IrjPnBDrQTS4BCkdYmJr/A=      50
+tvSqQgFPdxTdBR8CHHjnsKYNXL3QL4MZaWxIkCx1/w=      50
n/kcs8Ce7eCBaq67hYHAKIBKJ5WWs0DYp7i598N4Djk=      50
vzXJOOqDtW47xvgeDe0M/e+ujlPQceSGYEr/oFdqzcs=      50
M0KSLFkh0AT4Aqz0Y9XAwaq33XbRMPNTtDLnf4bBtj0=      50
Name: count, Length: 25038, dtype: int64

In [5]:
datahun = datasixm.groupby('hash_uid').filter(lambda x: len(x) > 100)
datahun

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
0,2017-09-19 13,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,219422,스타필드 코엑스몰점/샤이바나,코엑스몰점,Western Food Restaurants,"37.5120936275,127.059262544",서울특별시 강남구 삼성1동
1,2017-09-19 21,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,75192,롯데백화점 강남점,/슈즈에비뉴,Department Store,"37.49698724,127.05390349",서울 강남구 대치동 937
2,2017-09-21 15,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,212943,분당선 왕십리역,수원방면 4-3,Subway Station,"37.5605928695,127.038793266",서울 성동구 행당동 168-151
3,2017-09-23 13,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,219966,스타필드 코엑스몰점/Paul Bassett,코엑스몰점,Coffee Shop,"37.5138499364,127.059908286",서울 강남구 삼성1동
4,2017-09-23 14,++/2XJs5NMI9WqrJZCT+kkj1qVY9L0OfxHP1muGwi38=,R,218692,스타필드 코엑스몰점,/공수간/CJFOODWOTLD,Outlet/ Shopping Mall,"37.5117460309,127.058322765",서울 강남구 삼성동 159-9
...,...,...,...,...,...,...,...,...,...
5378681,2017-12-25 19,zywHRoQZE4xWnjlym9YXFSku1q8m0V9/MR6xTVhNBsQ=,R,168051,롯데마트 잠실점,/식품코너/비식품코너,Discount Department Store,"37.5115731629,127.096461095",서울 송파구 잠실동 40-1
5378682,2017-12-25 19,zywHRoQZE4xWnjlym9YXFSku1q8m0V9/MR6xTVhNBsQ=,R,61878,교보문고,잠실점/Hottracks,Bookstore,"37.5142866137,127.101097293",서울 송파구 신천동 7-18
5378683,2017-12-25 20,zywHRoQZE4xWnjlym9YXFSku1q8m0V9/MR6xTVhNBsQ=,R,31233,3POP PC,#101317#서울#송파구#잠실동,PC Cafe,"37.510896314,127.083929144",서울 송파구 잠실동 183-11
5378684,2017-12-25 20,zywHRoQZE4xWnjlym9YXFSku1q8m0V9/MR6xTVhNBsQ=,R,85904,서울2호선 잠실역,내선 3-1,Subway Station,"37.5130789634,127.099371627",서울 송파구 잠실동 32
5378685,2017-12-25 21,zywHRoQZE4xWnjlym9YXFSku1q8m0V9/MR6xTVhNBsQ=,R,31840,새마을식당,잠실신천점,Korean Food Restaurants,"37.510873176,127.083921097",서울 송파구 잠실동 183-11

In [6]:
datahun['hash_uid'].value_counts()

hash_uid
Uru5Avt875xZfeIlo5SijjLrq4DNsrF71gZQeJXrP8I=    8720
HmqVYaE6h9te/c29FCN6kdrOSwgHb/DaB5IEQ0f5EM8=    6617
gl/kKohNuZxHxWjV7kt041f5db5xLoH0aH0A3Zvm6Ro=    5287
kmZjtQg48O7hKADuqvIxzlWOkI/hosHdu4W4xb2JrAA=    5216
RPBB5wDJsF13FJqE0obViewGv4DsGu6g46hgnUzrgcQ=    4943
                                                ...
P8059NmbFX+cCCtZywnuCA8Begi9VUP2mvAx3kWnir4=     101
P8IoZlkWvjn9wlPNtF6mXz6Br5ySZTVrcqoaud75jkE=     101
taG/2vlqogldZZcYCPnHt13zS3Qtym6GSN7KlZgPCiM=     101
PJ477ps/U8scwPZMQt5ayyQzODjxRndvMebNNWbCHB8=     101
yFGSRcwqfcVUO8TfQF+Jrj5GIezl6tcYIe/c+CIh/AI=     101
Name: count, Length: 15986, dtype: int64

In [7]:
datathreehun = datasixm.groupby('hash_uid').filter(lambda x: len(x) > 300)
datathreehun['hash_uid'].value_counts()

hash_uid
Uru5Avt875xZfeIlo5SijjLrq4DNsrF71gZQeJXrP8I=    8720
HmqVYaE6h9te/c29FCN6kdrOSwgHb/DaB5IEQ0f5EM8=    6617
gl/kKohNuZxHxWjV7kt041f5db5xLoH0aH0A3Zvm6Ro=    5287
kmZjtQg48O7hKADuqvIxzlWOkI/hosHdu4W4xb2JrAA=    5216
RPBB5wDJsF13FJqE0obViewGv4DsGu6g46hgnUzrgcQ=    4943
                                                ...
TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=     301
a+gffFgyuTKFmN+JfTrl95p9NfmOsaP8P0Osr5eWpTk=     301
asnHzCkk/vG9UrVnhPh8d3wInr7iq2nFRdrgwQ9tFN4=     301
fap8Dh4LikjDcHy6IppirMHwKsUET1CamATfSjbNt+o=     301
cwdLDqZIr+g58Gzg7PeusrZQlCfFdHQd4pAqZTaClMw=     301
Name: count, Length: 4863, dtype: int64

In [8]:
lop = datasixm[datasixm['hash_uid'] == 'TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=']
lop

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
2632369,2017-09-16 16,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,301894,세븐일레븐,금천우림점,Convenience Store,"37.4548377916,126.899204738",서울특별시 금천구 시흥1동
2632370,2017-09-18 09,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울특별시 강남구 역삼1동
2632371,2017-09-18 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,162516,브라운돈가스,역삼점,Japanese Food Restaurants,"37.505241926,127.04075966",서울특별시 강남구 역삼1동
2632372,2017-09-18 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울특별시 강남구 역삼1동
2632373,2017-09-18 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울특별시 강남구 역삼1동
...,...,...,...,...,...,...,...,...,...
2632665,2017-12-23 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,148833,롯데시네마,안양일번가점,Movie Theater,"37.3996585674,126.920163795",경기 안양시 만안구 안양동 676-2
2632666,2017-12-23 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,148833,롯데시네마,안양일번가점,Movie Theater,"37.3996585674,126.920163795",경기 안양시 만안구 안양동 676-2
2632667,2017-12-23 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,293281,KFC,안양점,Burger/Sandwich,"37.3986954384,126.922278309",경기 안양시 만안구 안양동 674-140
2632668,2017-12-26 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,144569,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼동 662-14
2632669,2017-12-26 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,144569,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼동 662-14

In [9]:
lop['placename'].value_counts()

placename
로플랫                252
홈플러스 시흥점             7
ARITAUM              6
서울2호선                5
롯데시네마                3
CGV                  2
옥커피 호프               2
서울2호선 역삼역            2
서울2호선 사당역            1
선플러스치과의원             1
세븐일레븐                1
신한은행                 1
대도스포츠                1
스타벅스                 1
서울2호선 신촌역            1
IFC몰/CGV             1
소노야                  1
파리바게뜨                1
adidas               1
탑텐                   1
서울9호선 고속터미널역         1
서울9호선 선정릉역           1
서울2호선 교대역            1
스타필드 코엑스몰점/메가박스      1
구영회                  1
CU                   1
갑자흑염소                1
락꼬꼬                  1
브라운돈가스               1
KFC                  1
Name: count, dtype: int64

In [28]:
lop['addr'].value_counts()

addr
서울 강남구 역삼1동               136
서울 강남구 역삼동 662-14         109
서울특별시 강남구 역삼1동              9
서울 중구 명동                    8
서울 금천구 시흥동 992-47           7
서울 중구 회현동                   2
서울 서대문구 신촌로                 2
서울 금천구 시흥동 852-30           2
서울 중구 봉래동2가 122-21          2
경기 안양시 만안구 안양동 676-2        2
서울 영등포구 여의도동 23-1           1
서울 동작구 사당1동                 1
서울 마포구 대흥동                  1
서울 관악구 신림동 1641-2           1
서울 서대문구 창천동 20-25번지         1
서울 강남구 역삼동 804              1
서울 금천구 시흥동 883-7            1
서울특별시 금천구 시흥1동              1
서울 관악구 신림동 1467-10          1
서울 강남구 역삼동 705              1
서울 중구 광희동2가 250-2           1
서울 중구 명동1가 59-21            1
서울 서초구 반포3동                 1
서울 강남구 삼성2동                 1
서울 서초구 서초4동                 1
서울 강남구 삼성1동                 1
서울 강남구 역삼동 674-33           1
서울 금천구 시흥동 839              1
서울 금천구 시흥동 885-6            1
서울 강남구 역삼동 662-12           1
서울특별시 중구 회현동                1
경기 안양시 만안구 안양동 674-140      1
Name: count, dtype: int64

In [33]:
lop[lop['addr'] == '서울 강남구 역삼동 804']['placename']

2632607    서울2호선 역삼역
Name: placename, dtype: object

In [10]:
lop[lop['placename'] == '로플랫']['local_datehour'].tolist()

['2017-09-18 09',
 '2017-09-18 13',
 '2017-09-18 15',
 '2017-09-19 09',
 '2017-09-19 13',
 '2017-09-20 09',
 '2017-09-20 13',
 '2017-09-21 10',
 '2017-09-21 13',
 '2017-09-22 09',
 '2017-09-22 11',
 '2017-09-22 12',
 '2017-09-22 12',
 '2017-09-22 13',
 '2017-09-25 10',
 '2017-09-25 11',
 '2017-09-25 11',
 '2017-09-25 12',
 '2017-09-25 13',
 '2017-09-25 14',
 '2017-09-25 19',
 '2017-09-26 09',
 '2017-09-26 10',
 '2017-09-26 11',
 '2017-09-26 12',
 '2017-09-26 13',
 '2017-09-26 15',
 '2017-09-26 16',
 '2017-09-26 16',
 '2017-09-26 17',
 '2017-09-26 19',
 '2017-09-27 09',
 '2017-09-27 12',
 '2017-09-27 13',
 '2017-09-27 13',
 '2017-09-27 14',
 '2017-09-27 15',
 '2017-09-27 16',
 '2017-09-27 17',
 '2017-09-27 18',
 '2017-09-28 10',
 '2017-09-28 11',
 '2017-09-28 12',
 '2017-09-28 13',
 '2017-09-28 13',
 '2017-09-28 14',
 '2017-09-28 14',
 '2017-09-28 18',
 '2017-09-28 18',
 '2017-09-29 09',
 '2017-09-29 10',
 '2017-09-29 10',
 '2017-09-29 10',
 '2017-09-29 12',
 '2017-09-29 13',
 '2017-09-29 14',
 '2017-09-29 15',
 '2017-10-10 09',
 '2017-10-10 10',
 '2017-10-10 10',
 '2017-10-10 12',
 '2017-10-10 12',
 '2017-10-10 13',
 '2017-10-10 13',
 '2017-10-10 14',
 '2017-10-10 15',
 '2017-10-10 17',
 '2017-10-10 18',
 '2017-10-10 19',
 '2017-10-11 10',
 '2017-10-11 10',
 '2017-10-11 11',
 '2017-10-11 12',
 '2017-10-11 13',
 '2017-10-11 13',
 '2017-10-11 17',
 '2017-10-11 18',
 '2017-10-11 19',
 '2017-10-12 10',
 '2017-10-12 10',
 '2017-10-12 11',
 '2017-10-12 12',
 '2017-10-12 14',
 '2017-10-12 17',
 '2017-10-12 18',
 '2017-10-13 10',
 '2017-10-13 10',
 '2017-10-13 12',
 '2017-10-13 13',
 '2017-10-13 13',
 '2017-10-13 14',
 '2017-10-13 15',
 '2017-10-13 16',
 '2017-10-13 17',
 '2017-10-13 18',
 '2017-10-16 10',
 '2017-10-16 10',
 '2017-10-16 11',
 '2017-10-16 12',
 '2017-10-16 13',
 '2017-10-16 14',
 '2017-10-16 16',
 '2017-10-16 19',
 '2017-10-17 17',
 '2017-10-17 17',
 '2017-10-18 10',
 '2017-10-18 10',
 '2017-10-18 11',
 '2017-10-18 11',
 '2017-10-18 12',
 '2017-10-18 13',
 '2017-10-18 13',
 '2017-10-18 15',
 '2017-10-18 17',
 '2017-10-19 10',
 '2017-10-19 10',
 '2017-10-19 11',
 '2017-10-19 12',
 '2017-10-19 13',
 '2017-10-19 15',
 '2017-10-19 16',
 '2017-10-19 17',
 '2017-10-19 18',
 '2017-10-25 10',
 '2017-10-25 10',
 '2017-10-25 15',
 '2017-10-25 15',
 '2017-10-25 17',
 '2017-10-25 17',
 '2017-10-26 10',
 '2017-10-26 10',
 '2017-10-27 10',
 '2017-10-27 10',
 '2017-10-27 13',
 '2017-10-27 16',
 '2017-10-27 17',
 '2017-10-30 10',
 '2017-10-30 10',
 '2017-10-30 12',
 '2017-10-30 13',
 '2017-10-30 15',
 '2017-10-30 16',
 '2017-10-30 19',
 '2017-10-31 10',
 '2017-10-31 10',
 '2017-10-31 18',
 '2017-11-01 09',
 '2017-11-01 10',
 '2017-11-01 12',
 '2017-11-01 15',
 '2017-11-01 15',
 '2017-11-01 17',
 '2017-11-02 10',
 '2017-11-02 10',
 '2017-11-02 11',
 '2017-11-02 12',
 '2017-11-02 14',
 '2017-11-02 15',
 '2017-11-02 16',
 '2017-11-03 10',
 '2017-11-03 10',
 '2017-11-03 12',
 '2017-11-03 13',
 '2017-11-06 10',
 '2017-11-06 10',
 '2017-11-06 11',
 '2017-11-06 12',
 '2017-11-06 13',
 '2017-11-06 15',
 '2017-11-06 19',
 '2017-11-07 10',
 '2017-11-07 10',
 '2017-11-07 12',
 '2017-11-07 13',
 '2017-11-07 17',
 '2017-11-07 18',
 '2017-11-07 19',
 '2017-11-08 09',
 '2017-11-08 10',
 '2017-11-08 10',
 '2017-11-08 11',
 '2017-11-08 12',
 '2017-11-08 13',
 '2017-11-08 14',
 '2017-11-08 18',
 '2017-11-08 19',
 '2017-11-09 10',
 '2017-11-09 10',
 '2017-11-09 14',
 '2017-11-09 15',
 '2017-11-09 19',
 '2017-11-10 10',
 '2017-11-10 10',
 '2017-11-10 12',
 '2017-11-10 15',
 '2017-11-10 16',
 '2017-11-10 17',
 '2017-12-11 09',
 '2017-12-11 10',
 '2017-12-11 12',
 '2017-12-11 13',
 '2017-12-11 14',
 '2017-12-11 16',
 '2017-12-12 10',
 '2017-12-12 12',
 '2017-12-12 13',
 '2017-12-12 14',
 '2017-12-12 16',
 '2017-12-12 17',
 '2017-12-12 18',
 '2017-12-13 10',
 '2017-12-13 11',
 '2017-12-13 13',
 '2017-12-13 16',
 '2017-12-13 18',
 '2017-12-14 10',
 '2017-12-14 11',
 '2017-12-14 12',
 '2017-12-14 14',
 '2017-12-14 16',
 '2017-12-14 17',
 '2017-12-15 10',
 '2017-12-15 16',
 '2017-12-18 10',
 '2017-12-18 17',
 '2017-12-18 18',
 '2017-12-18 19',
 '2017-12-19 10',
 '2017-12-19 13',
 '2017-12-19 14',
 '2017-12-19 15',
 '2017-12-19 16',
 '2017-12-19 19',
 '2017-12-20 10',
 '2017-12-20 11',
 '2017-12-20 12',
 '2017-12-20 13',
 '2017-12-20 14',
 '2017-12-20 15',
 '2017-12-20 18',
 '2017-12-21 10',
 '2017-12-21 11',
 '2017-12-21 12',
 '2017-12-21 13',
 '2017-12-21 14',
 '2017-12-21 15',
 '2017-12-22 10',
 '2017-12-22 12',
 '2017-12-22 13',
 '2017-12-22 16',
 '2017-12-26 10',
 '2017-12-26 11']

In [11]:
lopc = lop[lop['placename'] == '로플랫'].copy()
lopc.insert(0, 'date', lopc['local_datehour'].str.split(" ", expand = True)[0])    
lopc.insert(1, 'hour', lopc['local_datehour'].str.split(" ", expand = True)[1])
lopc = lopc.drop(['local_datehour'], axis = 1)
lopc.groupby('date').apply(lambda x: x['hour'].tolist())

date
2017-09-18                                        [09, 13, 15]
2017-09-19                                            [09, 13]
2017-09-20                                            [09, 13]
2017-09-21                                            [10, 13]
2017-09-22                                [09, 11, 12, 12, 13]
2017-09-25                        [10, 11, 11, 12, 13, 14, 19]
2017-09-26            [09, 10, 11, 12, 13, 15, 16, 16, 17, 19]
2017-09-27                [09, 12, 13, 13, 14, 15, 16, 17, 18]
2017-09-28                [10, 11, 12, 13, 13, 14, 14, 18, 18]
2017-09-29                    [09, 10, 10, 10, 12, 13, 14, 15]
2017-10-10    [09, 10, 10, 12, 12, 13, 13, 14, 15, 17, 18, 19]
2017-10-11                [10, 10, 11, 12, 13, 13, 17, 18, 19]
2017-10-12                        [10, 10, 11, 12, 14, 17, 18]
2017-10-13            [10, 10, 12, 13, 13, 14, 15, 16, 17, 18]
2017-10-16                    [10, 10, 11, 12, 13, 14, 16, 19]
2017-10-17                                            [17, 17]
2017-10-18                [10, 10, 11, 11, 12, 13, 13, 15, 17]
2017-10-19                [10, 10, 11, 12, 13, 15, 16, 17, 18]
2017-10-25                            [10, 10, 15, 15, 17, 17]
2017-10-26                                            [10, 10]
2017-10-27                                [10, 10, 13, 16, 17]
2017-10-30                        [10, 10, 12, 13, 15, 16, 19]
2017-10-31                                        [10, 10, 18]
2017-11-01                            [09, 10, 12, 15, 15, 17]
2017-11-02                        [10, 10, 11, 12, 14, 15, 16]
2017-11-03                                    [10, 10, 12, 13]
2017-11-06                        [10, 10, 11, 12, 13, 15, 19]
2017-11-07                        [10, 10, 12, 13, 17, 18, 19]
2017-11-08                [09, 10, 10, 11, 12, 13, 14, 18, 19]
2017-11-09                                [10, 10, 14, 15, 19]
2017-11-10                            [10, 10, 12, 15, 16, 17]
2017-12-11                            [09, 10, 12, 13, 14, 16]
2017-12-12                        [10, 12, 13, 14, 16, 17, 18]
2017-12-13                                [10, 11, 13, 16, 18]
2017-12-14                            [10, 11, 12, 14, 16, 17]
2017-12-15                                            [10, 16]
2017-12-18                                    [10, 17, 18, 19]
2017-12-19                            [10, 13, 14, 15, 16, 19]
2017-12-20                        [10, 11, 12, 13, 14, 15, 18]
2017-12-21                            [10, 11, 12, 13, 14, 15]
2017-12-22                                    [10, 12, 13, 16]
2017-12-26                                            [10, 11]
dtype: object

In [12]:
lopc['hour'].value_counts()

hour
10    57
13    35
12    29
15    20
11    19
17    19
14    18
16    17
18    15
19    12
09    11
Name: count, dtype: int64

In [17]:
def totextvisited(dataframe, parentheses):
    
    df = dataframe.copy()
    df.insert(0, 'date', df['local_datehour'].str.split(" ", expand = True)[0])
    df.insert(1, 'hour', df['local_datehour'].str.split(" ", expand = True)[1])
    df = df.drop(['local_datehour'], axis = 1)
    df['tag'] = df['tag'].replace(np.nan, "")
    df['placename'] = df['placename'] + " " + df['tag'] 
    df = df.drop(['tag'], axis = 1)
    df = df.sort_values(by = ['date', 'hour'])
    
    print("A person's visit history from " + df.iloc[0, 0][5:10] + df.iloc[0, 0][4] + df.iloc[0, 0][0:4] 
          + " to " + df.iloc[len(df) - 1, 0][5:10] + df.iloc[len(df) - 1, 0][4] + df.iloc[len(df) - 1, 0][0:4] + " is as follows:\n")
    
    visited = {}
    visitedcataddr = {}
    
    for i in range(len(df)):
        irow = df.iloc[i, :]
        
        if irow['placename'][-1] == " ":
        
            pn = str(irow['placename'][:-1])
            
        else:
            
            pn = str(irow['placename'])
            
        if pn in visited.keys(): 
            
            visited[pn] += ", at " + irow['hour'] + " on " + irow['date'][5:10] + irow['date'][4] + irow['date'][0:4]
            
        elif pn not in visited.keys():
            
            visited.update({pn : " at " + irow['hour'] + " on " + irow['date'][5:10] + irow['date'][4] + irow['date'][0:4]})
            visitedcataddr.update({pn : [irow['cat'].lower(), str(irow['pid']), irow['addr'], 
                                        irow['lat_lng'].split(",")[0], irow['lat_lng'].split(",")[1]]})
            
    if parentheses == False:
        
        print("The person visited", end = "")
        
        for key, value in visited.items():
            if key == list(visited.keys())[-1]:
                print(" a " + visitedcataddr[key][0] + " named " + key 
                        + " located at " + visitedcataddr[key][2] + value + ".")
            else:
                print(" a " + visitedcataddr[key][0] + " named " + key 
                        + " located at " + str(visitedcataddr[key][2]) + value + ",", end = "")
                
    else:
        
        print("The person visited", end = "")
        
        for key, value in visited.items():
            if key == list(visited.keys())[-1]:
                print(" a " + visitedcataddr[key][0] + " named " + key + " (pid: " + visitedcataddr[key][1]
                        + ") located at " + visitedcataddr[key][2] 
                        + " (latitude: " + visitedcataddr[key][3] + ", longitude: " + visitedcataddr[key][4] + ")"
                        + value + ".")
            else:
                print(" a " + visitedcataddr[key][0] + " named " + key + " (pid: " + visitedcataddr[key][1]
                        + ") located at " + visitedcataddr[key][2] 
                        + " (latitude: " + visitedcataddr[key][3] + ", longitude: " + visitedcataddr[key][4] + ")"
                        + value + ",", end = "")

In [27]:
totextvisited(lop[lop['local_datehour'].str.contains('2017-10-1') == True], False)

A person's visit history from 10-10-2017 to 10-19-2017 is as follows:

The person visited a office named 로플랫 located at 서울 강남구 역삼1동 at 09 on 10-10-2017, at 10 on 10-10-2017, at 10 on 10-10-2017, at 12 on 10-10-2017, at 12 on 10-10-2017, at 13 on 10-10-2017, at 13 on 10-10-2017, at 14 on 10-10-2017, at 15 on 10-10-2017, at 17 on 10-10-2017, at 18 on 10-10-2017, at 19 on 10-10-2017, at 10 on 10-11-2017, at 10 on 10-11-2017, at 11 on 10-11-2017, at 12 on 10-11-2017, at 13 on 10-11-2017, at 13 on 10-11-2017, at 17 on 10-11-2017, at 18 on 10-11-2017, at 19 on 10-11-2017, at 10 on 10-12-2017, at 10 on 10-12-2017, at 11 on 10-12-2017, at 12 on 10-12-2017, at 14 on 10-12-2017, at 17 on 10-12-2017, at 18 on 10-12-2017, at 10 on 10-13-2017, at 10 on 10-13-2017, at 12 on 10-13-2017, at 13 on 10-13-2017, at 13 on 10-13-2017, at 14 on 10-13-2017, at 15 on 10-13-2017, at 16 on 10-13-2017, at 17 on 10-13-2017, at 18 on 10-13-2017, at 10 on 10-16-2017, at 10 on 10-16-2017, at 11 on 10-16-2017, at 12 on 10-16-2017, at 13 on 10-16-2017, at 14 on 10-16-2017, at 16 on 10-16-2017, at 19 on 10-16-2017, at 17 on 10-17-2017, at 17 on 10-17-2017, at 10 on 10-18-2017, at 10 on 10-18-2017, at 11 on 10-18-2017, at 11 on 10-18-2017, at 12 on 10-18-2017, at 13 on 10-18-2017, at 13 on 10-18-2017, at 15 on 10-18-2017, at 17 on 10-18-2017, at 10 on 10-19-2017, at 10 on 10-19-2017, at 11 on 10-19-2017, at 12 on 10-19-2017, at 13 on 10-19-2017, at 15 on 10-19-2017, at 16 on 10-19-2017, at 17 on 10-19-2017, at 18 on 10-19-2017, a dental clinic named 선플러스치과의원 치과 located at 서울 강남구 역삼동 705 at 22 on 10-10-2017, a subway station named 서울2호선 사당역 내선 5-1 located at 서울 동작구 사당1동 at 21 on 10-13-2017, a bank named 신한은행 시흥동점 located at 서울 금천구 시흥동 883-7 at 17 on 10-14-2017, a discount department store named 홈플러스 시흥점 /비식품 located at 서울 금천구 시흥동 992-47 at 18 on 10-14-2017, a discount department store named 홈플러스 시흥점 /푸드코트 located at 서울 금천구 시흥동 992-47 at 18 on 10-14-2017, at 18 on 10-14-2017, a others(alchoholic beverages) named 옥커피 호프 located at 서울 금천구 시흥동 852-30 at 18 on 10-14-2017.

In [24]:
import pandas as pd
pd.set_option('display.max_rows', None)
lopoc = lop[lop['local_datehour'].str.contains('2017-10-1') == True]
lopoc

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
2632452,2017-10-10 09,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632453,2017-10-10 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632454,2017-10-10 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632455,2017-10-10 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632456,2017-10-10 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632457,2017-10-10 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632458,2017-10-10 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632459,2017-10-10 14,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632460,2017-10-10 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632461,2017-10-10 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632462,2017-10-10 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632463,2017-10-10 19,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632464,2017-10-10 22,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,60623,선플러스치과의원,치과,Dental Clinic,"37.5047772684,127.046987079",서울 강남구 역삼동 705
2632465,2017-10-11 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632466,2017-10-11 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632467,2017-10-11 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632468,2017-10-11 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632469,2017-10-11 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632470,2017-10-11 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632471,2017-10-11 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632472,2017-10-11 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632473,2017-10-11 19,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632474,2017-10-12 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632475,2017-10-12 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632476,2017-10-12 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632477,2017-10-12 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632478,2017-10-12 14,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632479,2017-10-12 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632480,2017-10-12 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632481,2017-10-13 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632482,2017-10-13 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632483,2017-10-13 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632484,2017-10-13 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632485,2017-10-13 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632486,2017-10-13 14,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632487,2017-10-13 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632488,2017-10-13 16,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632489,2017-10-13 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632490,2017-10-13 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632491,2017-10-13 21,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,84006,서울2호선 사당역,내선 5-1,Subway Station,"37.4766019659,126.981321909",서울 동작구 사당1동
2632492,2017-10-14 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,45275,신한은행,시흥동점,Bank,"37.4541079958,126.901177838",서울 금천구 시흥동 883-7
2632493,2017-10-14 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,167961,홈플러스 시흥점,/비식품,Discount Department Store,"37.451651071,126.901166774",서울 금천구 시흥동 992-47
2632494,2017-10-14 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,168718,홈플러스 시흥점,/푸드코트,Discount Department Store,"37.4517250647,126.901071221",서울 금천구 시흥동 992-47
2632495,2017-10-14 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,168718,홈플러스 시흥점,/푸드코트,Discount Department Store,"37.4517250647,126.901071221",서울 금천구 시흥동 992-47
2632496,2017-10-14 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,292127,옥커피 호프,NaN,Others(Alchoholic Beverages),"37.4524074237,126.90583331",서울 금천구 시흥동 852-30
2632497,2017-10-16 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632498,2017-10-16 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632499,2017-10-16 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632500,2017-10-16 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632501,2017-10-16 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632502,2017-10-16 14,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632503,2017-10-16 16,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632504,2017-10-16 19,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632505,2017-10-17 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632506,2017-10-17 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632507,2017-10-18 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632508,2017-10-18 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632509,2017-10-18 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632510,2017-10-18 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632511,2017-10-18 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632512,2017-10-18 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632513,2017-10-18 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632514,2017-10-18 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632515,2017-10-18 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632516,2017-10-19 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632517,2017-10-19 10,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632518,2017-10-19 11,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632519,2017-10-19 12,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632520,2017-10-19 13,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632521,2017-10-19 15,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632522,2017-10-19 16,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632523,2017-10-19 17,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동
2632524,2017-10-19 18,TOR4+viyobHOtxCeC2W1a3cYjexF91IcBJxY9cOJock=,R,257621,로플랫,NaN,Office,"37.5059546487,127.040727726",서울 강남구 역삼1동

In [26]:
len(lopoc[lopoc['placename'] == '로플랫'])

66

In [13]:
datasixm[datasixm['cat'] == 'Office']['placename'].value_counts()

placename
로플랫        8026
로플랫 회의실    1023
nka         690
굿닥          667
위메프         545
           ...
오스코텍          1
랩지노믹스         1
메덱스           1
청호나이스         1
창원시새마을회       1
Name: count, Length: 330, dtype: int64

In [14]:
datasixm[datasixm['placename'] == '로플랫 회의실']

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
185016,2017-08-09 17,028t5Q5Bm6BkLZ2Ij/3jb7UqTWKtUbpjmG6zZ4+rXE8=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울특별시 강남구 역삼1동
255244,2017-07-28 09,0olAGL/eYxk9E4uRKWrkDuWtt6fH1DaVXsGfpIzIjCw=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",NaN
255246,2017-07-28 13,0olAGL/eYxk9E4uRKWrkDuWtt6fH1DaVXsGfpIzIjCw=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",NaN
255253,2017-07-31 17,0olAGL/eYxk9E4uRKWrkDuWtt6fH1DaVXsGfpIzIjCw=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",NaN
255257,2017-08-01 10,0olAGL/eYxk9E4uRKWrkDuWtt6fH1DaVXsGfpIzIjCw=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",NaN
...,...,...,...,...,...,...,...,...,...
5267988,2017-12-08 13,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5267991,2017-12-08 14,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268022,2017-12-11 10,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268026,2017-12-11 11,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268028,2017-12-11 12,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14

In [15]:
lopmeet = datasixm[datasixm['hash_uid'] == 'ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=']
lopmeet[lopmeet['placename'] == '로플랫 회의실']

,local_datehour,hash_uid,mode,pid,placename,tag,cat,lat_lng,addr
5266741,2017-10-10 13,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼1동
5266748,2017-10-10 16,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼1동
5266753,2017-10-10 18,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼1동
5266807,2017-10-16 18,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼1동
5266839,2017-10-18 11,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼1동
...,...,...,...,...,...,...,...,...,...
5267988,2017-12-08 13,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5267991,2017-12-08 14,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268022,2017-12-11 10,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268026,2017-12-11 11,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14
5268028,2017-12-11 12,ykQ5OFt1ptYMDaHxfhv72bnSr7SSfnSAGF5zBR3kqjM=,R,168466,로플랫 회의실,NaN,Office,"37.5059342525,127.04072345",서울 강남구 역삼동 662-14

In [16]:
lopmc = lopmeet[lopmeet['placename'] == '로플랫'].copy()
lopmc.insert(0, 'date', lopmc['local_datehour'].str.split(" ", expand = True)[0])    
lopmc.insert(1, 'hour', lopmc['local_datehour'].str.split(" ", expand = True)[1])
lopmc = lopmc.drop(['local_datehour'], axis = 1)
lopmc.groupby('date').apply(lambda x: x['hour'].tolist())

date
2017-10-10    [09, 10, 10, 12, 12, 12, 13, 13, 13, 13, 14, 1...
2017-10-11         [10, 10, 10, 10, 11, 11, 11, 12, 14, 15, 16]
2017-10-12                             [10, 13, 18, 18, 20, 20]
2017-10-13                     [09, 09, 10, 10, 11, 11, 13, 13]
2017-10-16             [10, 10, 12, 12, 13, 13, 15, 18, 20, 20]
2017-10-17    [09, 09, 10, 10, 10, 11, 12, 13, 17, 17, 18, 1...
2017-10-18    [10, 10, 10, 10, 11, 13, 14, 16, 16, 16, 16, 1...
2017-10-19    [09, 09, 10, 13, 13, 14, 15, 15, 15, 17, 18, 1...
2017-10-20             [09, 09, 13, 13, 13, 14, 15, 15, 17, 18]
2017-10-22         [13, 13, 14, 14, 14, 15, 15, 16, 17, 23, 23]
2017-10-23     [00, 00, 00, 09, 09, 10, 10, 11, 12, 13, 13, 13]
2017-10-24    [10, 10, 10, 14, 14, 15, 15, 16, 16, 17, 17, 1...
2017-10-25     [10, 10, 10, 11, 12, 13, 13, 13, 17, 17, 17, 18]
2017-10-26    [09, 09, 10, 11, 12, 13, 13, 15, 15, 17, 18, 1...
2017-10-27    [09, 09, 09, 10, 11, 12, 13, 14, 14, 14, 15, 1...
2017-10-28    [14, 14, 14, 15, 15, 16, 17, 17, 18, 19, 19, 2...
2017-10-29    [00, 00, 00, 01, 01, 01, 02, 03, 03, 04, 04, 0...
2017-10-30    [11, 11, 11, 13, 14, 14, 14, 15, 15, 16, 17, 1...
2017-10-31    [09, 09, 10, 10, 11, 11, 11, 11, 12, 12, 13, 1...
2017-11-01    [09, 09, 10, 10, 10, 10, 11, 11, 11, 11, 12, 1...
2017-11-02    [09, 09, 11, 11, 12, 12, 13, 13, 14, 14, 14, 1...
2017-11-03    [10, 10, 11, 11, 11, 12, 12, 13, 14, 14, 14, 1...
2017-11-06    [10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 1...
2017-11-07    [09, 09, 10, 10, 12, 12, 12, 12, 13, 13, 13, 1...
2017-11-08    [10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 1...
2017-11-09    [09, 09, 10, 11, 11, 12, 12, 12, 13, 13, 14, 1...
2017-11-10    [00, 01, 01, 01, 01, 02, 02, 02, 02, 03, 03, 0...
2017-11-13         [10, 10, 10, 11, 11, 12, 13, 13, 14, 15, 15]
2017-11-14                     [11, 11, 12, 13, 14, 14, 15, 16]
2017-11-15    [09, 09, 10, 10, 10, 11, 11, 11, 12, 12, 12, 1...
2017-11-16    [09, 09, 10, 10, 10, 10, 11, 11, 12, 12, 13, 1...
2017-11-17    [09, 09, 10, 10, 11, 11, 12, 12, 14, 14, 15, 1...
2017-11-20    [09, 09, 10, 10, 10, 10, 10, 11, 11, 12, 13, 1...
2017-11-21    [09, 09, 10, 10, 11, 11, 11, 12, 12, 13, 13, 1...
2017-11-22    [09, 10, 10, 11, 12, 12, 12, 13, 13, 13, 14, 1...
2017-11-23                             [12, 12, 13, 14, 15, 18]
2017-11-24                         [10, 11, 12, 14, 14, 14, 15]
2017-11-29    [13, 13, 14, 15, 15, 16, 17, 17, 18, 18, 19, 1...
2017-11-30    [09, 09, 09, 10, 10, 11, 11, 11, 12, 12, 12, 1...
2017-12-01    [10, 10, 11, 12, 13, 13, 13, 14, 14, 14, 15, 1...
2017-12-04    [10, 10, 11, 12, 13, 13, 14, 14, 14, 14, 15, 1...
2017-12-05    [10, 10, 10, 10, 11, 11, 12, 12, 12, 12, 13, 1...
2017-12-06    [09, 10, 10, 10, 11, 11, 11, 12, 12, 13, 14, 1...
2017-12-07    [10, 10, 10, 10, 11, 11, 11, 12, 13, 13, 13, 1...
2017-12-08    [12, 12, 13, 13, 14, 14, 14, 14, 15, 15, 16, 1...
2017-12-11    [09, 10, 10, 10, 11, 12, 12, 12, 13, 14, 14, 1...
dtype: object